#!/bin/sh -e
export MPP_INIT_QUIET=1
$LAUNCH ./alltoall? -- <<EOF
-c10 -w10       simple 100 16
-c10 -w10 -d -g simple 100
-c10 -w10 -g -x simple 100
-c10 -w10 -d -x simple 100 20
-c10 -w10 -d -p simple 100 24
-c10 -w10 -p -y simple 100 28
-c10 -w10 -pxy  simple 100 32
EOF
exit 0
