# get a oshmem image in public Dockerhub
FROM npmolino/bale_public_gupc


RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
	vim less curl

COPY . /opt/bale_private

WORKDIR /opt/bale_private

RUN ./run_autoreconf
ENV UPC gupc
ENV PLATFORM gupc
RUN ./install.sh -u

RUN echo "---- done with install ----"

# run as non-root user
RUN adduser --disabled-password --gecos "" bale_user



