# get a gupc image in public Dockerhub
FROM npmolino/bale_public_gupc

RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
	vim less curl python3 python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

RUN pip install pytest 

COPY . /opt/bale_private

WORKDIR /opt/bale_private/src/bale_classic

RUN ./bootstrap.sh
ENV UPC gupc
ENV PLATFORM gupc
RUN ./make_bale -u

RUN echo "---- done with install ----"

# run as non-root user
# bale_user exists from Dockerfile in the bale_public_gupc image at this point
#RUN adduser --disabled-password --gecos "" bale_user



