FROM gupc:latest

RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
	pandoc vim less curl python3 python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

RUN pip install pytest

# copy bale from host into container (the host should be sitting at the top level of bale_private)
COPY . /opt/bale_private

WORKDIR /opt/bale_private/src/bale_classic

RUN ./bootstrap.sh
ENV UPC gupc
ENV PLATFORM gupc
RUN ./install.sh -u

RUN echo "---- done with install ----"

WORKDIR /opt/bale_private/src/bale_classic/apps

RUN pytest -s -P=/opt/bale_private/src/bale_classic/build_gupc/bin --node_range=1,3,1 

