[package]
name = "pshmem"
description = "Partitioned Shared Memory (pShmem)"
version = "0.1.0"
authors = ["Bill Carlson <wwc559@gmail.com>"]
edition = "2018"

[dependencies]
shmem = { path="../shmem" }
