# get a oshmem image in public Dockerhub
FROM npmolino/bale_public_oshmem4.0.3:v1 


RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
	vim less curl python3 python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip

RUN pip install pytest 

COPY . /opt/bale_private

WORKDIR /opt/bale_private/src/bale_classic

RUN ./run_autoreconf
ENV CC oshcc 
ENV PLATFORM oshmem
RUN ./install.sh -s

RUN echo "---- done with install ----"

# run as non-root user
RUN adduser --disabled-password --gecos "" bale_user


