name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file oshmem/Dockerfile_github_action --tag bale_test:github_action
    - name: Run the Docker image
      run: docker run bale_test:github_action oshrun -n 1 build_oshmem/bin/histo -M 1 -c 1
